### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by cxhernandez** [Pappulab/localCIDER#1]
Hey @alexholehouse:

Would you be interested in a PR that adds py3 compatibility?

**Comment by alexholehouse** [comment]
Very - this is awesome! 

I'm about to leave for a conference (and we're about to submit this work for publication) so I don't want to rush so I'm not going to accept right now, BUT when I get back (Wed) I'll accept and integrate anything else in. I want to add in a bunch more tests so would rather finish them, make sure they're working in 2.7.x and then merge py3 support and ensure all the tests still run.

This is extremely excellent - hugely appreciated.

**Comment by alexholehouse** [comment]
Also thanks for the PEP8 style update - was this done with [autopep8](https://pypi.python.org/pypi/autopep8/) - I wasn't familiar with it before now, but I assume you didn't make all ~2000 changes by hand!

**Comment by cxhernandez** [comment]
No problem! Thanks for making such a useful package :+1:

The only changes I made were to [`setup.py`](https://github.com/cxhernandez/localCIDER/commit/27a9a87dae8a9387af28b197ec37d7b299c19a48). Tried installing in 2.7.9 and 3.4 and everything seemed to work OK. Everything else was done with autopep8 :pray:
