### ISSUE TITLE
typo in setPhosPhoSites

### ISSUE THREAD

**Issue by jeanmanguy** [Pappulab/localCIDER#4]
https://github.com/Pappulab/localCIDER/blob/5134fe8c9ef322bf8f889aff01544b2a26ecaa7f/localcider/backend/sequence.py#L1623

Hi,
This is just a small typo. Thank you for your work, I hope a new version of localCider will be available from `pip` soon.

**Comment by alexholehouse** [comment]
Thank you! Fixed (a while ago, I just failed to close the comment)
